import React, { useState } from 'react';
import { useDispatch, useSelector } from 'react-redux';
import { useNavigate } from 'react-router-dom';
import toast from 'react-hot-toast';

import api from '../../services/api';
import { loginStart, loginSuccess, loginFailure } from './userSlice';
import GoogleLoginButton from './GoogleLoginButton'; 
import { AUTH_LOGIN, AUTH_REGISTER } from '../../services/apiRoutes'; 

const LoginModal = ({ isOpen, onClose }) => {
  const [isSignInForm, setSignInForm] = useState(true);
  const [formData, setFormData] = useState({ username: '', email: '', password: '' });
  const [registerError, setRegisterError] = useState(null);
  const [isRegisterLoading, setIsRegisterLoading] = useState(false);

  const dispatch = useDispatch();
  const navigate = useNavigate();
  const { loading: loginLoading, error: loginError } = useSelector((state) => state.user);

  if (!isOpen) return null;

  const handleChange = (e) => {
    setFormData({ ...formData, [e.target.name]: e.target.value });
  };

  const handleSubmit = async (e) => {
    e.preventDefault();
    setRegisterError(null);

    if (isSignInForm) {
      // --- DJOSER JWT LOGIN EXECUTION ---
      dispatch(loginStart());

      try {
        // STEP 1: Get the access and refresh tokens
        const response = await api.post(AUTH_LOGIN, {
          email: formData.email,
          password: formData.password
        });
        
        const { access, refresh, is_admin } = response.data;

        // Save tokens immediately so our API instance can use them
        localStorage.setItem('access_token', access); 
        localStorage.setItem('refresh_token', refresh);

        // STEP 2: Fetch the user's details using Djoser's built-in /me/ endpoint
        const userResponse = await api.get('auth/users/me/', {
            headers: {
                Authorization: `Bearer ${access}`
            }
        });
        
        // --- ADDED: Extract the profile_picture from the response ---
        const { username, id, profile_picture } = userResponse.data;

        // STEP 3: Save to localStorage so it survives page reloads
        localStorage.setItem('user_info', JSON.stringify({ username, profile_picture, is_admin }));
        localStorage.setItem('id', id);

        // --- ADDED: Dispatch profile_picture to Redux ---
        dispatch(loginSuccess({ 
          token: access, 
          user: { username, id, profile_picture, is_admin } 
        }));
        
        onClose(); 
        navigate('/'); 

      } catch (err) {
        console.error("Login Failure Event:", err);
        const errorMessage = err.response?.data?.detail || "Invalid credential alignment. Check verification state.";
        dispatch(loginFailure(errorMessage));
      }
    } else {
      // --- DJOSER SECURE REGISTRATION ENGINE ---
      setIsRegisterLoading(true);
      try {
        const dataToSend = {
          username: formData.username,
          email: formData.email,
          password: formData.password
        };

        await api.post(AUTH_REGISTER, dataToSend);
        
        toast.success("Registration sequence initiated! Check your inbox.");

        setSignInForm(true);
        setFormData({ username: '', email: '', password: '' });

      } catch (err) {
        console.error("Registration Failure Event:", err);
        
        // Handle potential nested field array feedback maps generated by Djoser
        let processedError = "Registration rejected.";
        if (err.response?.data) {
          const firstKey = Object.keys(err.response.data)[0];
          const rawError = err.response.data[firstKey];
          processedError = Array.isArray(rawError) ? rawError[0] : rawError;
        }
        setRegisterError(processedError);
        // toast.error(processedError);
      } finally {
        setIsRegisterLoading(false);
      }
    }
  };

  const toggleSignInForm = () => {
    setSignInForm(!isSignInForm);
    setRegisterError(null);
    if (loginError) dispatch(loginFailure(null)); 
  };

  const displayError = isSignInForm ? loginError : registerError;
  const isLoading = isSignInForm ? loginLoading : isRegisterLoading;

  return (
    <div 
      className="fixed inset-0 z-50 flex justify-center items-center bg-black/70 backdrop-blur-md p-4"
      onClick={onClose} 
    >
      <div 
        className="w-full max-w-sm bg-[#151a28] p-8 rounded-xl border border-gray-800 shadow-2xl relative"
        onClick={(e) => e.stopPropagation()} 
      >
        
        <button 
          onClick={onClose}
          className="absolute top-4 right-4 text-gray-500 hover:text-cyan-400 transition-colors"
        >
          <svg className="w-6 h-6" fill="none" viewBox="0 0 24 24" stroke="currentColor">
            <path strokeLinecap="round" strokeLinejoin="round" strokeWidth={2} d="M6 18L18 6M6 6l12 12" />
          </svg>
        </button>

        <div className="mb-6 text-center mt-2">
          <h2 className="text-3xl font-black uppercase tracking-wider text-transparent bg-clip-text bg-gradient-to-r from-cyan-400 to-blue-500 mb-1">
            {isSignInForm ? 'Welcome Back' : 'Join the Game'}
          </h2>
          <p className="text-sm text-gray-500 font-medium">
            {isSignInForm ? 'Log in to continue your session' : 'Create an account to get started'}
          </p>
        </div>

        {displayError && (
          <div className="bg-red-900/30 text-red-400 px-4 py-3 rounded-lg mb-6 text-sm text-center border border-red-800/50">
            {displayError}
          </div>
        )}

        <form onSubmit={handleSubmit} className="space-y-4">
          {!isSignInForm && (
            <div>
              <input
                type="text"
                name="username"
                value={formData.username}
                onChange={handleChange}
                placeholder="Username"
                required
                className="w-full px-4 py-3 bg-[#0b0f19] border border-gray-700 rounded-lg text-white placeholder-gray-600 focus:outline-none focus:border-cyan-500 focus:ring-1 focus:ring-cyan-500 transition-colors"
              />
            </div>
          )}
          <div>
            <input
              type="email"
              name="email"
              value={formData.email}
              onChange={handleChange}
              placeholder="Email address"
              required
              className="w-full px-4 py-3 bg-[#0b0f19] border border-gray-700 rounded-lg text-white placeholder-gray-600 focus:outline-none focus:border-cyan-500 focus:ring-1 focus:ring-cyan-500 transition-colors"
            />
          </div>
          <div>
            <input
              type="password"
              name="password"
              value={formData.password}
              onChange={handleChange}
              placeholder="Password"
              required
              className="w-full px-4 py-3 bg-[#0b0f19] border border-gray-700 rounded-lg text-white placeholder-gray-600 focus:outline-none focus:border-cyan-500 focus:ring-1 focus:ring-cyan-500 transition-colors"
            />
            
            {/* --- FORGOT PASSWORD LINK --- */}
            {isSignInForm && (
              <div className="flex justify-end mt-2">
                <button
                  type="button"
                  onClick={() => {
                    onClose(); 
                    navigate('/forgot-password'); 
                  }}
                  className="text-xs text-cyan-400 hover:text-cyan-300 font-medium transition-colors"
                >
                  Forgot Password?
                </button>
              </div>
            )}
            {/* -------------------------------- */}

          </div>

          <button
            type="submit"
            disabled={isLoading}
            className={`w-full font-bold py-3 rounded-lg uppercase tracking-wide transition-all flex justify-center items-center mt-6
              ${isLoading 
                ? 'bg-gray-700 text-gray-500 cursor-not-allowed' 
                : 'bg-cyan-600 hover:bg-cyan-500 text-white shadow-[0_0_15px_rgba(8,145,178,0.3)] hover:shadow-[0_0_25px_rgba(8,145,178,0.5)]'
              }`}
          >
            {isLoading 
              ? (isSignInForm ? 'Connecting...' : 'Registering...') 
              : (isSignInForm ? 'Login' : 'Create Account')
            }
          </button>
        </form>

        <div className="mt-6 flex items-center justify-center space-x-2">
          <span className="h-[1px] w-full bg-gray-700"></span>
          <span className="text-xs text-gray-500 font-bold uppercase tracking-widest">OR</span>
          <span className="h-[1px] w-full bg-gray-700"></span>
        </div>

        <div className="mt-4 flex justify-center">
          <GoogleLoginButton onClose={onClose} />
        </div>

        <p className="mt-6 text-center text-sm text-gray-500">
          {isSignInForm ? "New player? " : 'Already registered? '}
          <button 
            type="button"
            onClick={toggleSignInForm}
            className="text-cyan-400 hover:text-cyan-300 font-semibold transition-colors uppercase tracking-wide"
          >
            {isSignInForm ? 'Sign Up' : 'Log In'}
          </button>
        </p>

      </div>
    </div>
  );
};

export default LoginModal;