import React, { useState } from 'react';
import { useParams, useNavigate } from 'react-router-dom';
import api from '../../services/api';
import { AUTH_PASSWORD_RESET_CONFIRM } from '../../services/apiRoutes';

const ResetPasswordConfirm = () => {
  // Grab the UID and Token generated by Djoser from the email URL
  const { uid, token } = useParams();
  const navigate = useNavigate();

  const [formData, setFormData] = useState({ new_password: '', re_new_password: '' });
  const [status, setStatus] = useState('idle');
  const [errorMessage, setErrorMessage] = useState('');

  const handleChange = (e) => {
    setFormData({ ...formData, [e.target.name]: e.target.value });
  };

  const handleSubmit = async (e) => {
    e.preventDefault();
    setErrorMessage('');

    if (formData.new_password !== formData.re_new_password) {
      setErrorMessage("Passwords do not match.");
      return;
    }

    setStatus('loading');

    try {
      // Djoser requires uid, token, and the new password
      await api.post(AUTH_PASSWORD_RESET_CONFIRM, {
        uid: uid,
        token: token,
        new_password: formData.new_password,
      });
      
      setStatus('success');
      setTimeout(() => {
        navigate('/'); // Send them home so they can log in normally
      }, 3000);

    } catch (err) {
      console.error("Reset confirmation failed:", err);
      setStatus('error');
      
      // Extract Djoser password validation errors (e.g., "password is too common")
      let processedError = "Failed to reset password. The link may have expired.";
      if (err.response?.data?.new_password) {
        processedError = err.response.data.new_password[0];
      }
      setErrorMessage(processedError);
    }
  };

  return (
    <div className="min-h-screen bg-[#0a0a0c] flex justify-center items-center p-4">
      <div className="w-full max-w-md bg-[#151a28] p-8 rounded-xl border border-gray-800 shadow-2xl">
        <div className="mb-6 text-center">
          <h2 className="text-2xl font-black uppercase tracking-wider text-white mb-2">
            Create New Password
          </h2>
        </div>

        {status === 'success' ? (
          <div className="bg-green-900/30 text-green-400 px-4 py-4 rounded-lg text-center border border-green-800/50">
            <p className="font-bold uppercase tracking-wider mb-1">Password Updated!</p>
            <p className="text-xs">Redirecting to login...</p>
          </div>
        ) : (
          <form onSubmit={handleSubmit} className="space-y-4">
            {status === 'error' && (
              <div className="bg-red-900/30 text-red-400 px-4 py-3 rounded-lg text-sm border border-red-800/50">
                {errorMessage}
              </div>
            )}
            
            <div>
              <input
                type="password"
                name="new_password"
                value={formData.new_password}
                onChange={handleChange}
                placeholder="New Password"
                required
                className="w-full px-4 py-3 bg-[#0b0f19] border border-gray-700 rounded-lg text-white placeholder-gray-600 focus:outline-none focus:border-cyan-500"
              />
            </div>
            <div>
              <input
                type="password"
                name="re_new_password"
                value={formData.re_new_password}
                onChange={handleChange}
                placeholder="Confirm New Password"
                required
                className="w-full px-4 py-3 bg-[#0b0f19] border border-gray-700 rounded-lg text-white placeholder-gray-600 focus:outline-none focus:border-cyan-500"
              />
            </div>

            <button
              type="submit"
              disabled={status === 'loading'}
              className={`w-full font-bold py-3 rounded-lg uppercase tracking-wide transition-all
                ${status === 'loading' 
                  ? 'bg-gray-700 text-gray-500 cursor-not-allowed' 
                  : 'bg-cyan-600 hover:bg-cyan-500 text-white shadow-[0_0_15px_rgba(8,145,178,0.3)]'
                }`}
            >
              {status === 'loading' ? 'Saving...' : 'Set Password'}
            </button>
          </form>
        )}
      </div>
    </div>
  );
};

export default ResetPasswordConfirm;